//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soap_client_ws.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReference1.BanqueService")]
    public interface BanqueService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getCompteRequest", ReplyAction="http://ws/BanqueService/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soap_client_ws.ServiceReference1.getCompteResponse getCompte(soap_client_ws.ServiceReference1.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getCompteRequest", ReplyAction="http://ws/BanqueService/getCompteResponse")]
        System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.getCompteResponse> getCompteAsync(soap_client_ws.ServiceReference1.getCompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/conversionEuroToDHRequest", ReplyAction="http://ws/BanqueService/conversionEuroToDHResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soap_client_ws.ServiceReference1.conversionEuroToDHResponse conversionEuroToDH(soap_client_ws.ServiceReference1.conversionEuroToDHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/conversionEuroToDHRequest", ReplyAction="http://ws/BanqueService/conversionEuroToDHResponse")]
        System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.conversionEuroToDHResponse> conversionEuroToDHAsync(soap_client_ws.ServiceReference1.conversionEuroToDHRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getComptesRequest", ReplyAction="http://ws/BanqueService/getComptesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soap_client_ws.ServiceReference1.getComptesResponse getComptes(soap_client_ws.ServiceReference1.getComptesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getComptesRequest", ReplyAction="http://ws/BanqueService/getComptesResponse")]
        System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.getComptesResponse> getComptesAsync(soap_client_ws.ServiceReference1.getComptesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private System.DateTime dateCreationField;
        
        private bool dateCreationFieldSpecified;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateCreation {
            get {
                return this.dateCreationField;
            }
            set {
                this.dateCreationField = value;
                this.RaisePropertyChanged("dateCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreationSpecified {
            get {
                return this.dateCreationFieldSpecified;
            }
            set {
                this.dateCreationFieldSpecified = value;
                this.RaisePropertyChanged("dateCreationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        public getCompteRequest() {
        }
        
        public getCompteRequest(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public soap_client_ws.ServiceReference1.compte @return;
        
        public getCompteResponse() {
        }
        
        public getCompteResponse(soap_client_ws.ServiceReference1.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conversionEuroToDH", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class conversionEuroToDHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double montant;
        
        public conversionEuroToDHRequest() {
        }
        
        public conversionEuroToDHRequest(double montant) {
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conversionEuroToDHResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class conversionEuroToDHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public conversionEuroToDHResponse() {
        }
        
        public conversionEuroToDHResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptes", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getComptesRequest {
        
        public getComptesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptesResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getComptesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public soap_client_ws.ServiceReference1.compte[] @return;
        
        public getComptesResponse() {
        }
        
        public getComptesResponse(soap_client_ws.ServiceReference1.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueServiceChannel : soap_client_ws.ServiceReference1.BanqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueServiceClient : System.ServiceModel.ClientBase<soap_client_ws.ServiceReference1.BanqueService>, soap_client_ws.ServiceReference1.BanqueService {
        
        public BanqueServiceClient() {
        }
        
        public BanqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soap_client_ws.ServiceReference1.getCompteResponse soap_client_ws.ServiceReference1.BanqueService.getCompte(soap_client_ws.ServiceReference1.getCompteRequest request) {
            return base.Channel.getCompte(request);
        }
        
        public soap_client_ws.ServiceReference1.compte getCompte(string code) {
            soap_client_ws.ServiceReference1.getCompteRequest inValue = new soap_client_ws.ServiceReference1.getCompteRequest();
            inValue.code = code;
            soap_client_ws.ServiceReference1.getCompteResponse retVal = ((soap_client_ws.ServiceReference1.BanqueService)(this)).getCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.getCompteResponse> soap_client_ws.ServiceReference1.BanqueService.getCompteAsync(soap_client_ws.ServiceReference1.getCompteRequest request) {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.getCompteResponse> getCompteAsync(string code) {
            soap_client_ws.ServiceReference1.getCompteRequest inValue = new soap_client_ws.ServiceReference1.getCompteRequest();
            inValue.code = code;
            return ((soap_client_ws.ServiceReference1.BanqueService)(this)).getCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soap_client_ws.ServiceReference1.conversionEuroToDHResponse soap_client_ws.ServiceReference1.BanqueService.conversionEuroToDH(soap_client_ws.ServiceReference1.conversionEuroToDHRequest request) {
            return base.Channel.conversionEuroToDH(request);
        }
        
        public double conversionEuroToDH(double montant) {
            soap_client_ws.ServiceReference1.conversionEuroToDHRequest inValue = new soap_client_ws.ServiceReference1.conversionEuroToDHRequest();
            inValue.montant = montant;
            soap_client_ws.ServiceReference1.conversionEuroToDHResponse retVal = ((soap_client_ws.ServiceReference1.BanqueService)(this)).conversionEuroToDH(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.conversionEuroToDHResponse> soap_client_ws.ServiceReference1.BanqueService.conversionEuroToDHAsync(soap_client_ws.ServiceReference1.conversionEuroToDHRequest request) {
            return base.Channel.conversionEuroToDHAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.conversionEuroToDHResponse> conversionEuroToDHAsync(double montant) {
            soap_client_ws.ServiceReference1.conversionEuroToDHRequest inValue = new soap_client_ws.ServiceReference1.conversionEuroToDHRequest();
            inValue.montant = montant;
            return ((soap_client_ws.ServiceReference1.BanqueService)(this)).conversionEuroToDHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soap_client_ws.ServiceReference1.getComptesResponse soap_client_ws.ServiceReference1.BanqueService.getComptes(soap_client_ws.ServiceReference1.getComptesRequest request) {
            return base.Channel.getComptes(request);
        }
        
        public soap_client_ws.ServiceReference1.compte[] getComptes() {
            soap_client_ws.ServiceReference1.getComptesRequest inValue = new soap_client_ws.ServiceReference1.getComptesRequest();
            soap_client_ws.ServiceReference1.getComptesResponse retVal = ((soap_client_ws.ServiceReference1.BanqueService)(this)).getComptes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.getComptesResponse> soap_client_ws.ServiceReference1.BanqueService.getComptesAsync(soap_client_ws.ServiceReference1.getComptesRequest request) {
            return base.Channel.getComptesAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_client_ws.ServiceReference1.getComptesResponse> getComptesAsync() {
            soap_client_ws.ServiceReference1.getComptesRequest inValue = new soap_client_ws.ServiceReference1.getComptesRequest();
            return ((soap_client_ws.ServiceReference1.BanqueService)(this)).getComptesAsync(inValue);
        }
    }
}
